### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by Juli199696** [Albeoris/Septerra#1]
Hey i came to your repository by checking out a forum. Is your project still alive? Also i have problems with unpacking the files with the "Steam" version of the game. Gives me a lot of error. Second, would you think it is possible to compile your binary for ARM devices so a Raspberry Pi 4 as example could run it? Is your binary even a "working" exe that can replace the septerra.exe or is it just an injection?

**Comment by Juli199696** [comment]
I get many errors like that 

System.AggregateException: Failed to extract files. ---> System.NotSupportedException: [1C]
   bei Septerra.Core.TXEncoding.ToText(Byte bt) in C:\Git\C#\Septerra\Septerra.Core\Formats\TX\TXEncoding.cs:Zeile 13.
   bei Septerra.Core.TXReader.ReadStrings(Stream stream) in C:\Git\C#\Septerra\Septerra.Core\Formats\TX\TXReader.cs:Zeile 137.
   bei Septerra.Core.TextTarget.Write(ArraySegment`1 segment, String outputPath, UInt16 expectedVersion) in C:\Git\C#\Septerra\Septerra.Core\Formats\Targets\TextTarget.cs:Zeile 18.
   bei Septerra.Core.DbExtractor.Extract(DbPackage package, IdxEntry entry, ThreadContext context) in C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:Zeile 311.
   bei Septerra.Core.DbExtractor.Extract(Object state) in C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:Zeile 127.

**Comment by Albeoris** [comment]
>  is it just an injection?

It is just injection.

> Is your project still alive?

I did the main thing I dreamed about - turn-based battles without a long wait. :)

I would like to continue to analyze the levels and write an editor as a result, but this will take a lot of time, and I'm not sure if anyone needs this.

**Comment by Albeoris** [comment]
> System.AggregateException: Failed to extract files. ---> System.NotSupportedException: [1C]
> bei Septerra.Core.TXEncoding.ToText(Byte bt) 

What the language?

I tested it only on the English version. I think you have an unsupported character (1C) in your text, and I don’t know how to translate it into a text representation. Tell me how to get your version of the game, I'll try to see what the problem is.

**Comment by Galajus** [comment]
Hello, I have similar problem, when i instal my language pack from this place https://www.mediafire.com/file/fgrdi9162k7knus/Septerra_Core_PL.rar/file
your patch crashes and doesn't work :(
Can you help with this? Thanks!

**Comment by Albeoris** [comment]
@Galajus , I looked at that. Guys, what is this version? Is this an old disk version? Not Steam?

Or is it some kind of fan translation? Text data seems corrupted.

**Comment by Galajus** [comment]
I'm use steam version. In oryginal english your patch works great but with this language pack i have errors :/

This is probably translation from old game cd version

**Comment by Albeoris** [comment]
Apparently, this patch incorrectly stored the text description. Judging by it, the first record begins after the data section.

![](https://i.imgur.com/khprBpz.png)

**Comment by Albeoris** [comment]
Oh hell, I see. The author simply appended new lines to the end, but did not change the size in the header.

**Comment by Albeoris** [comment]
> Tori: "Co sяychaя, Mayu?"

Also, it seems it using your own encoding. This is not a problem if it is written in the .exe file, but if not, part of the characters will be replaced with spaces. I just don’t know how to export them. Anyway, the game also changes the character that is not in the encoding to a space.

**Comment by Albeoris** [comment]
Try it:
https://github.com/Albeoris/Septerra/releases/tag/v2020.05.25

**Comment by Albeoris** [comment]
Feel free to make new issues if something goes wrong.

**Comment by professorpalmer** [comment]
Hey my guy trying to contact you... sorry to keep blowing you up.

I'm not getting the F key to work. Is it determined in some .ini somewhere? It works on my buddys setup no problem, all the other changes work as well. Just not the F key. Any way to map/remap it on my end?

**Comment by Albeoris** [comment]
> 
> 
> Hey my guy trying to contact you... sorry to keep blowing you up.
> 
> I'm not getting the F key to work. Is it determined in some .ini somewhere? It works on my buddys setup no problem, all the other changes work as well. Just not the F key. Any way to map/remap it on my end?

This?
https://github.com/Albeoris/Septerra/issues/2

**Comment by rellikmil** [comment]
@Albeoris Did I understand correctly that this version will not work for Russian language?

**Comment by Albeoris** [comment]
> @Albeoris Did I understand correctly that this version will not work for Russian language?

@rellikmil why not? Let me know if you have some kind of problems. You need Russian fonts and correct encoding in .exe file.

**Comment by LexLiven** [comment]
> > @Albeoris Did I understand correctly that this version will not work for Russian language?
> 
> @rellikmil why not? Let me know if you have some kind of problems. You need Russian fonts and correct encoding in .exe file.

It cannot neither unpack russian files nor convert them.
I can share any file for you to try.
For 20 years I wanted to edit russian text to correct some mistakes...

`
----------------------------
Failed to unpack game data.
----------------------------
System.AggregateException: Failed to extract files. ---> System.NotSupportedException: Invalid magic number: ????? b?
   в Septerra.Core.DbExtractor.Extract(DbPackage package, IdxEntry entry, ThreadContext context) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 296
   в Septerra.Core.DbExtractor.Extract(Object state) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 125
   --- Конец трассировки внутреннего стека исключений ---
   в Septerra.Core.DbExtractor.CheckExceptions() в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 76
   в Septerra.Core.DbExtractor.Dispose() в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 63
   в Septerra.Core.DbExtractor.Enqueue(DbPackage package, IdxEntry entry) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 86
   в Septerra.UnpackGamePackagesCoroutine.Execute() в C:\Git\C#\Septerra\Septerra\Coroutines\Unpack\UnpackGamePackagesCoroutine.cs:строка 32
   в Septerra.Program.Unpack(ProgramArguments arguments) в C:\Git\C#\Septerra\Septerra\Program.cs:строка 138
---> (Внутреннее исключение #0) System.NotSupportedException: Invalid magic number: ????? b?
   в Septerra.Core.DbExtractor.Extract(DbPackage package, IdxEntry entry, ThreadContext context) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 296
   в Septerra.Core.DbExtractor.Extract(Object state) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 125<---

---> (Внутреннее исключение #1) System.NotSupportedException: Invalid magic number: ????????
   в Septerra.Core.DbExtractor.Extract(DbPackage package, IdxEntry entry, ThreadContext context) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 296
   в Septerra.Core.DbExtractor.Extract(Object state) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 125<---

---> (Внутреннее исключение #2) System.NotSupportedException: Invalid magic number: ????????
   в Septerra.Core.DbExtractor.Extract(DbPackage package, IdxEntry entry, ThreadContext context) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 296
   в Septerra.Core.DbExtractor.Extract(Object state) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 125<---

---> (Внутреннее исключение #3) System.NotSupportedException: Invalid magic number: ????????
   в Septerra.Core.DbExtractor.Extract(DbPackage package, IdxEntry entry, ThreadContext context) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 296
   в Septerra.Core.DbExtractor.Extract(Object state) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 125<---

----------------------------
unpack [gameFolder] [outputFolder] [-convert] [-rename]
 Example: unpack . .\Data -convert
  will unpack resources from the current folder to the \Data folder, convert all known resources to the user-friendly formats and rename known files.
`

**Comment by Albeoris** [comment]
> > > @Albeoris Did I understand correctly that this version will not work for Russian language?
> > 
> > 
> > @rellikmil why not? Let me know if you have some kind of problems. You need Russian fonts and correct encoding in .exe file.
> 
> It cannot neither unpack russian files nor convert them. I can share any file for you to try. For 20 years I wanted to edit russian text to correct some mistakes...
> 
> ## `
> ## Failed to unpack game data.
> System.AggregateException: Failed to extract files. ---> System.NotSupportedException: Invalid magic number: ????? b? в Septerra.Core.DbExtractor.Extract(DbPackage package, IdxEntry entry, ThreadContext context) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 296 в Septerra.Core.DbExtractor.Extract(Object state) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 125 --- Конец трассировки внутреннего стека исключений --- в Septerra.Core.DbExtractor.CheckExceptions() в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 76 в Septerra.Core.DbExtractor.Dispose() в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 63 в Septerra.Core.DbExtractor.Enqueue(DbPackage package, IdxEntry entry) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 86 в Septerra.UnpackGamePackagesCoroutine.Execute() в C:\Git\C#\Septerra\Septerra\Coroutines\Unpack\UnpackGamePackagesCoroutine.cs:строка 32 в Septerra.Program.Unpack(ProgramArguments arguments) в C:\Git\C#\Septerra\Septerra\Program.cs:строка 138 ---> (Внутреннее исключение #0) System.NotSupportedException: Invalid magic number: ????? b? в Septerra.Core.DbExtractor.Extract(DbPackage package, IdxEntry entry, ThreadContext context) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 296 в Septerra.Core.DbExtractor.Extract(Object state) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 125<---
> 
> ---> (Внутреннее исключение #1) System.NotSupportedException: Invalid magic number: ???????? в Septerra.Core.DbExtractor.Extract(DbPackage package, IdxEntry entry, ThreadContext context) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 296 в Septerra.Core.DbExtractor.Extract(Object state) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 125<---
> 
> ---> (Внутреннее исключение #2) System.NotSupportedException: Invalid magic number: ???????? в Septerra.Core.DbExtractor.Extract(DbPackage package, IdxEntry entry, ThreadContext context) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 296 в Septerra.Core.DbExtractor.Extract(Object state) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 125<---
> 
> ---> (Внутреннее исключение #3) System.NotSupportedException: Invalid magic number: ???????? в Septerra.Core.DbExtractor.Extract(DbPackage package, IdxEntry entry, ThreadContext context) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 296 в Septerra.Core.DbExtractor.Extract(Object state) в C:\Git\C#\Septerra\Septerra.Core\Formats\DB\DbExtractor.cs:строка 125<---
> 
> unpack [gameFolder] [outputFolder] [-convert] [-rename] Example: unpack . .\Data -convert will unpack resources from the current folder to the \Data folder, convert all known resources to the user-friendly formats and rename known files. `

Да, скидывай, конечно.

**Comment by rellikmil** [comment]
Стоило догадаться конечно, ну да ладно. Стало быть, Вы и на ZOG присутствуете? Надо наконец довести это дело до конца

**Comment by Albeoris** [comment]
.-.

Пиши в телегу по одноименному нику, если что. Но да, на ZOG'е присутствую.
Блин, пришла весна, ожили от спячки все проекты, даже про 8ую финалку вспомнили. -_-
Так что не обещаю, что будет быстро.

Я правильно понимаю, что речь идёт о русификаторе с ZoG поставленному поверх последней Steam/Gog версии?

**Comment by LexLiven** [comment]
> Да, скидывай, конечно.

Ну раз ты русскоязычный фанат Септерры, то вряд ли у меня есть что-то, чего нет у тебя :)
Я text.db русифицированный хотел отправить.

**Comment by rellikmil** [comment]
Я так понял, что группу никто никакую не создавал, верно?

**Comment by LexLiven** [comment]
Прошу прощения, замотался. Создал, отправил приглашения.
