### ISSUE TITLE
FileNotFound Exception when running launch.bat

### ISSUE THREAD

**Issue by andyperfect** [Albeoris/Septerra#2]
I'm getting the following error when running launch.bat from the most recent release

https://i.imgur.com/NCCAEjI.png

The dll referenced in the stack trace (Septerra.Native.dll) definitely exists in the Launcher directory. The resulting data folder is empty after the error, but if I run the Launch.bat file again, the game loads fine in windowed mode, but the included "f to speed up battle wait" change is not present. This is on a brand new windows 10 pro install so I'm wondering if it's related to that somehow? I know it's been ages since a change on this project, but any help on this would be amazing.

**Comment by andyperfect** [comment]
Update on this: I pulled down the source, and realized the project targeted dotnet 4.7.1. Installed that, which now runs the launch.bat, but now the game crashes instantly once the window opens.

My best guess at this point is that Windows 10 now comes bundled with dotnet 4.8, which is not compatible somehow with the method of loading the dll's. Before I installed 4.7.1, the extraction would fail, but the game would boot via the Launch.bat on the 2nd attempt since it saw the Data folder present. But no extraction or F key injection occurred.

Once I installed dotnet 4.7.1 (I did it automatically from a prompt within VS as it told me it targeted a different version than what I had) it allowed the extraction to occur, but now the game window crashes once opening. My best guess at this point is something related to mismatched dotnet versions.

**Comment by andyperfect** [comment]
Finally isolated the issue, for anyone that happens across this. The solution for me was to pull down the source and build all of the projects myself. I then copied the Output directory's contents into the Launcher directory of the provided release. That then worked. I believe something about new windows installs causes the provided release files to not work.

**Comment by LexLiven** [comment]
Are there any solution without rebuilding entire project?

> Finally isolated the issue, for anyone that happens across this. The solution for me was to pull down the source and build all of the projects myself. I then copied the Output directory's contents into the Launcher directory of the provided release. That then worked. I believe something about new windows installs causes the provided release files to not work.

Can you share built result?
